# Define the goal
string performative
string sender
int32 rank
string receiver
string language
string ontology
string urgency
string content
string timestamp
---
# Define the result
uint32 act_outcome
---
# Define a feedback message
float32 time2finish
